version: '3'

services:
  postgres-nest:
    image: postgres:13
    container_name: postgres-nest
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-nest:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']

volumes:
  postgres-nest:
